webtalk_init -webtalk_dir D:/sem 2/Computer Organization and Degital Design/Nano_processor/Nano_processor.sim/sim_1/behav/xsim/xsim.dir/NanoProcessor_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 11 11:11:40 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "44884d85b4b05811a75631c57f6b7b5f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "280d31de23d64c81b847593d1cb9e228" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "169" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6456_KB" -context "xsim\\usage"
webtalk_transmit -clientid 928734559 -regid "" -xml D:/sem 2/Computer Organization and Degital Design/Nano_processor/Nano_processor.sim/sim_1/behav/xsim/xsim.dir/NanoProcessor_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/sem 2/Computer Organization and Degital Design/Nano_processor/Nano_processor.sim/sim_1/behav/xsim/xsim.dir/NanoProcessor_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/sem 2/Computer Organization and Degital Design/Nano_processor/Nano_processor.sim/sim_1/behav/xsim/xsim.dir/NanoProcessor_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
